// <auto-generated />
using System;
using BeeEye.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeeEye.Persistence.Migrations
{
    [DbContext(typeof(BeeEyeDbContext))]
    partial class BeeEyeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeeEye.Persistence.Entities.ActionOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("RealisedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId")
                        .IsUnique();

                    b.ToTable("action_outcomes", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.ApprovalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId", "StepNumber")
                        .IsUnique();

                    b.ToTable("approval_steps", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.IngestionBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceObject")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("SourceObject", "Checksum")
                        .IsUnique();

                    b.ToTable("ingestion_batches", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ChassisNo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("DateOfManufacture")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfPurchase")
                        .HasColumnType("date");

                    b.Property<decimal>("HoldingCostPerDay")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngestionBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Interior")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly?>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.HasIndex("Location", "Model", "Variant");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.ManagementDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ImplementedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImplementedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ModificationJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpenedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RecommendationId")
                        .IsUnique()
                        .HasDatabaseName("IX_management_decisions_open_per_recommendation")
                        .HasFilter("\"Outcome\" = 'Open'");

                    b.HasIndex("Outcome", "OpenedAtUtc");

                    b.ToTable("management_decisions", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("integer");

                    b.Property<int>("InboundStock")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngestionBatchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("SupersededByPartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.PartCompatibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngestionBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Model");

                    b.HasIndex("PartId", "Model")
                        .IsUnique();

                    b.ToTable("part_compatibilities", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.PartSupersession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngestionBatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewPartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OldPartId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NewPartId");

                    b.HasIndex("OldPartId");

                    b.ToTable("part_supersessions", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.PartUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngestionBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceEventId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("Model");

                    b.HasIndex("PartId", "UsageDate");

                    b.ToTable("part_usages", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("AnalysisDate")
                        .HasColumnType("date");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("AssumptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DatasetVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ExpectedOutcome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ImpactSar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerRole")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RulesetVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SubjectRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SupersededByRecommendationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisDate");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("SubjectRef");

                    b.HasIndex("SupersededByRecommendationId");

                    b.HasIndex("CurrentStatus", "Priority");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.RecommendationStatusEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId", "AtUtc");

                    b.ToTable("recommendation_status_events", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.SalesFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("DateOfManufacture")
                        .HasColumnType("date");

                    b.Property<bool>("DiscountApplied")
                        .HasColumnType("boolean");

                    b.Property<int>("DiscountPct")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngestionBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Interior")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("IsRamadan")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("Revenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("SaleMonth")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("integer");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RowHash")
                        .IsUnique();

                    b.HasIndex("SaleMonth");

                    b.HasIndex("Model", "Variant", "Location", "SaleMonth");

                    b.ToTable("sales_facts", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.ServiceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngestionBatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LaborHours")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("MileageBand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MileageKm")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("MonthsSinceSale")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("Vin");

                    b.HasIndex("Model", "ServiceDate");

                    b.ToTable("service_events", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.VehicleSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngestionBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("SaleMonth")
                        .HasColumnType("date");

                    b.Property<int>("SaleYear")
                        .HasColumnType("integer");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.HasIndex("Model", "SaleMonth");

                    b.ToTable("vehicle_sales", (string)null);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.ActionOutcome", b =>
                {
                    b.HasOne("BeeEye.Persistence.Entities.ManagementDecision", "Decision")
                        .WithOne("ActionOutcome")
                        .HasForeignKey("BeeEye.Persistence.Entities.ActionOutcome", "DecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.ApprovalStep", b =>
                {
                    b.HasOne("BeeEye.Persistence.Entities.ManagementDecision", "Decision")
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.ManagementDecision", b =>
                {
                    b.HasOne("BeeEye.Persistence.Entities.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.Recommendation", b =>
                {
                    b.HasOne("BeeEye.Persistence.Entities.Recommendation", null)
                        .WithMany()
                        .HasForeignKey("SupersededByRecommendationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.RecommendationStatusEvent", b =>
                {
                    b.HasOne("BeeEye.Persistence.Entities.Recommendation", "Recommendation")
                        .WithMany("StatusEvents")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.ManagementDecision", b =>
                {
                    b.Navigation("ActionOutcome");

                    b.Navigation("ApprovalSteps");
                });

            modelBuilder.Entity("BeeEye.Persistence.Entities.Recommendation", b =>
                {
                    b.Navigation("StatusEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
